---
#components:
#  - ../base

resources:
  - ../base
#  - configmap.yaml

#namespace: dev-namespace

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.3.0
    namespace: grafana
    releaseName: grafana
    valuesFile: ../base/values.yaml
    additionalValuesFiles:
      - values.yaml
