---
components:
  - ../base

resources:
  - configmap.yaml

namespace: dev-namespace

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.3.0
    namespace: dev-namespace
    releaseName: grafana-dev-releasename
    valuesFile: ../base/values.yaml
    additionalValuesFiles:
      - values.yaml