# ---
# environments:
#   dev:
#     values:
#       - "{{ .Values.global.environment }}-values.yaml"
#   staging:
#     values:
#       - "{{ .Values.global.environment }}/values.yaml"
#   prod:
#     values:
#       - "{{ .Values.global.environment }}/values.yaml"
---
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
  - name: "grafana"
    namespace: "{{ .Values.global.namespace }}"
    chart: grafana/grafana
    version: "{{ .Values.global.chartVersion }}"
    values:
      - values.yaml
      #- "{{ .Environment.Name }}/values.yaml"